---
include:
  - "lib/**/*.rb"
  - "tasks/**/*.rake"
exclude:
  - spec/**/*
  - test/**/*
  - vendor/**/*
  - ".home/**/*"
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths:
  - /usr/lib/ruby/3.2.0
plugins: []
max_files: 5000
